# Site settings
title: Li Xiang - The salted fish in clear water bay
description: "A blog about Li Xiang ..."
#baseurl: "/space-jekyll-template" # for test: remove string '/space-jekyll-template' to ''
#url: "http://victorvoid.github.io/space-jekyll-template/" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# User settings
username: Li Xiang
user_title: Li Xiang - salted fish
email: xlidq@connect.ust.hk
twitter_username: lixiang_ragnar
github_username:  az123zx123
gplus_username:  none
linkedin_public_url: 想-李-40420814b # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: none
profile_picture: https://az123zx123.github.io/personal/profile.jpg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /personal
      key_trigger: 1
    - title: my posts
      url: /personal/posts
      key_trigger: 2
    - title: series
      url: /personal/series
      key_trigger: 3
    - title: study
      url: /personal/study
      key_trigger: 4
    - title: about me
      url: /personal/about
      key_trigger: 5
  section_2:
    - title: github
      url: http://www.github.com/az123zx123
      new_tab: true
      key_trigger: g
    - title: facebook
      url: http://www.facebook.com/profile.php?id=100021979440011
      key_trigger: f
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: HKUST_Canteen_Visualization
    url: https://github.com/Sausage-SONG/HKUST_Canteen_Visualization
  - name: escape
    url: https://github.com/az123zx123/escape
  - name: ALS_prediction
    url: https://github.com/az123zx123/Attributes-evaluation-for-ALS-disease-progression
  - name: flight-shout
    url: https://github.com/az123zx123/flight-shout

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
